[project]
name = "hackathon-ai-upgrad"
version = "0.1.0"
description = ""
authors = [
    {name = "Shubham Prakash",email = "shubhamprakash702@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0,<3.14"
dependencies = [
    "langchain (>=0.3.27,<0.4.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "langchain-openai (>=0.3.32,<0.4.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "pymongo (>=4.14.1,<5.0.0)",
    "langchain-google-genai (>=2.1.10,<3.0.0)",
    "youtube-transcript-api (>=1.2.2,<2.0.0)",
    "ffmpeg-python (>=0.2.0,<0.3.0)",
    "moviepy (==1.0.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
